### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AIM132** [schrojunzhang/KarmaDock#25]
Traceback (most recent call last):
  File "/home/L/miniconda3/envs/karmadock/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/L/KarmaDock/dataset/dataloader_obj.py", line 31, in __call__
    elem = batch[0]
IndexError: list index out of range

Does anyone know how to fix this, thanks

**Comment by KFIVE23** [comment]
> Traceback (most recent call last): File "/home/L/miniconda3/envs/karmadock/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/prefetch_generator/**init**.py", line 80, in run for item in self.generator: File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in **next** data = self._next_data() File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/L/miniconda3/envs/karmadock/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch return self.collate_fn(data) File "/home/L/KarmaDock/dataset/dataloader_obj.py", line 31, in **call** elem = batch[0] IndexError: list index out of range
> 
> Does anyone know how to fix this, thanks

Have you solved this problem?
